/* Generated By:JavaCC: Do not edit this line. CalculadoraDeValoresLogicosConstants.java */
package Exe5;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CalculadoraDeValoresLogicosConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OP_LOGICO_E = 5;
  /** RegularExpression Id. */
  int OP_LOGICO_OU = 6;
  /** RegularExpression Id. */
  int VERDADEIRO = 7;
  /** RegularExpression Id. */
  int FALSO = 8;
  /** RegularExpression Id. */
  int IDENT = 9;
  /** RegularExpression Id. */
  int ATRIB = 10;
  /** RegularExpression Id. */
  int IGUAL = 11;
  /** RegularExpression Id. */
  int REAL = 12;
  /** RegularExpression Id. */
  int HEXADECIMAL = 13;
  /** RegularExpression Id. */
  int VARIAVEL = 14;
  /** RegularExpression Id. */
  int OP_LOGICO_JAVA = 15;
  /** RegularExpression Id. */
  int OP_RELACIONAL = 16;
  /** RegularExpression Id. */
  int OP_RELACIONAL_JAVA = 17;
  /** RegularExpression Id. */
  int OP_RELACIONAL_PASCAL = 18;
  /** RegularExpression Id. */
  int ABRE_PARENTESES = 19;
  /** RegularExpression Id. */
  int FECHA_PARENTESES = 20;
  /** RegularExpression Id. */
  int ADICAO = 21;
  /** RegularExpression Id. */
  int SUBTRACAO = 22;
  /** RegularExpression Id. */
  int MULTIPLICACAO = 23;
  /** RegularExpression Id. */
  int DIVISAO = 24;
  /** RegularExpression Id. */
  int MODULO = 25;
  /** RegularExpression Id. */
  int PT_VIRG = 26;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"AND\"",
    "\"OR\"",
    "<VERDADEIRO>",
    "<FALSO>",
    "<IDENT>",
    "\":=\"",
    "\"=\"",
    "<REAL>",
    "<HEXADECIMAL>",
    "<VARIAVEL>",
    "\"!\"",
    "<OP_RELACIONAL>",
    "<OP_RELACIONAL_JAVA>",
    "\"<>\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\" %\"",
    "\";\"",
  };

}
