/* Generated By:JavaCC: Do not edit this line. NumerosRomanosArabicosConstants.java */
package Exe1;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface NumerosRomanosArabicosConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EXIBE = 5;
  /** RegularExpression Id. */
  int IDENT = 6;
  /** RegularExpression Id. */
  int ATRIB = 7;
  /** RegularExpression Id. */
  int IGUAL = 8;
  /** RegularExpression Id. */
  int ADICAO = 9;
  /** RegularExpression Id. */
  int PT_VIRG = 10;
  /** RegularExpression Id. */
  int NUM = 11;
  /** RegularExpression Id. */
  int UM = 12;
  /** RegularExpression Id. */
  int DOIS = 13;
  /** RegularExpression Id. */
  int TRES = 14;
  /** RegularExpression Id. */
  int QUATRO = 15;
  /** RegularExpression Id. */
  int CINCO = 16;
  /** RegularExpression Id. */
  int SEIS = 17;
  /** RegularExpression Id. */
  int SETE = 18;
  /** RegularExpression Id. */
  int OITO = 19;
  /** RegularExpression Id. */
  int NOVE = 20;
  /** RegularExpression Id. */
  int DEZ = 21;
  /** RegularExpression Id. */
  int VINTE = 22;
  /** RegularExpression Id. */
  int TRINTA = 23;
  /** RegularExpression Id. */
  int QUARENTA = 24;
  /** RegularExpression Id. */
  int CINQUENTA = 25;
  /** RegularExpression Id. */
  int SESSENTA = 26;
  /** RegularExpression Id. */
  int SETENTA = 27;
  /** RegularExpression Id. */
  int OITENTA = 28;
  /** RegularExpression Id. */
  int NOVENTA = 29;
  /** RegularExpression Id. */
  int CEM = 30;
  /** RegularExpression Id. */
  int DUZENTOS = 31;
  /** RegularExpression Id. */
  int TREZENTOS = 32;
  /** RegularExpression Id. */
  int QUATROCENTOS = 33;
  /** RegularExpression Id. */
  int QUINHETOS = 34;
  /** RegularExpression Id. */
  int SEISCENTOS = 35;
  /** RegularExpression Id. */
  int SETECENTOS = 36;
  /** RegularExpression Id. */
  int OITOCENTOS = 37;
  /** RegularExpression Id. */
  int NOVECENTOS = 38;
  /** RegularExpression Id. */
  int MIL = 39;
  /** RegularExpression Id. */
  int DOISMIL = 40;
  /** RegularExpression Id. */
  int TREISMIL = 41;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"exibe\"",
    "<IDENT>",
    "\":=\"",
    "\"=\"",
    "\"+\"",
    "\";\"",
    "<NUM>",
    "\"I\"",
    "\"II\"",
    "\"III\"",
    "\"IV\"",
    "\"V\"",
    "\"VI\"",
    "\"VII\"",
    "\"VIII\"",
    "\"IX\"",
    "\"X\"",
    "\"XX\"",
    "\"XXX\"",
    "\"XL\"",
    "\"L\"",
    "\"LX\"",
    "\"LXX\"",
    "\"LXXX\"",
    "\"XC\"",
    "\"C\"",
    "\"CC\"",
    "\"CCC\"",
    "\"CD\"",
    "\"D\"",
    "\"DC\"",
    "\"DCC\"",
    "\"DCCC\"",
    "\"CM\"",
    "\"M\"",
    "\"MM\"",
    "\"MMM\"",
  };

}
