/* Generated By:JavaCC: Do not edit this line. ClassificadorDeTokensDoJavaCPascalConstants.java */
package Exe2;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ClassificadorDeTokensDoJavaCPascalConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OP_LOGICO_PASCAL = 5;
  /** RegularExpression Id. */
  int IDENT = 6;
  /** RegularExpression Id. */
  int ATRIB = 7;
  /** RegularExpression Id. */
  int IGUAL = 8;
  /** RegularExpression Id. */
  int REAL = 9;
  /** RegularExpression Id. */
  int NATURAIS = 10;
  /** RegularExpression Id. */
  int DIGITOS = 11;
  /** RegularExpression Id. */
  int HEXADECIMAL = 12;
  /** RegularExpression Id. */
  int VARIAVEL = 13;
  /** RegularExpression Id. */
  int OP_LOGICO_JAVA = 14;
  /** RegularExpression Id. */
  int OP_RELACIONAL = 15;
  /** RegularExpression Id. */
  int OP_RELACIONAL_JAVA = 16;
  /** RegularExpression Id. */
  int OP_RELACIONAL_PASCAL = 17;
  /** RegularExpression Id. */
  int ABRE_PARENTESES = 18;
  /** RegularExpression Id. */
  int FECHA_PARENTESES = 19;
  /** RegularExpression Id. */
  int ADICAO = 20;
  /** RegularExpression Id. */
  int SUBTRACAO = 21;
  /** RegularExpression Id. */
  int MULTIPLICACAO = 22;
  /** RegularExpression Id. */
  int DIVISAO = 23;
  /** RegularExpression Id. */
  int MODULO = 24;
  /** RegularExpression Id. */
  int PT_VIRG = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<OP_LOGICO_PASCAL>",
    "<IDENT>",
    "\":=\"",
    "\"=\"",
    "<REAL>",
    "<NATURAIS>",
    "<DIGITOS>",
    "<HEXADECIMAL>",
    "<VARIAVEL>",
    "<OP_LOGICO_JAVA>",
    "<OP_RELACIONAL>",
    "<OP_RELACIONAL_JAVA>",
    "\"<>\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\" %\"",
    "\";\"",
  };

}
