/* Generated By:JavaCC: Do not edit this line. CalculadoraDeConjuntosConstants.java */
package Exe6;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CalculadoraDeConjuntosConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int VAR = 5;
  /** RegularExpression Id. */
  int IDENT = 6;
  /** RegularExpression Id. */
  int NUM = 7;
  /** RegularExpression Id. */
  int VIRG = 8;
  /** RegularExpression Id. */
  int PT_VIRG = 9;
  /** RegularExpression Id. */
  int PONTO = 10;
  /** RegularExpression Id. */
  int IGUAL = 11;
  /** RegularExpression Id. */
  int UNIAO = 12;
  /** RegularExpression Id. */
  int INTERSECAO = 13;
  /** RegularExpression Id. */
  int ESTA_CONTIDO = 14;
  /** RegularExpression Id. */
  int PERTENCE = 15;
  /** RegularExpression Id. */
  int ABRE_CHAVES = 16;
  /** RegularExpression Id. */
  int FECHA_CHAVES = 17;
  /** RegularExpression Id. */
  int ABRE_PAR = 18;
  /** RegularExpression Id. */
  int FECHA_PAR = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<VAR>",
    "<IDENT>",
    "<NUM>",
    "\",\"",
    "\";\"",
    "\".\"",
    "\"=\"",
    "\"U\"",
    "\"^\"",
    "\"C\"",
    "\"E\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
  };

}
