/* Generated By:JavaCC: Do not edit this line. AnalisadorlexicoConstants.java */
package comp_etp_4;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalisadorlexicoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMENTARIO_BLOC = 6;
  /** RegularExpression Id. */
  int COMENTARIO_LIN = 7;
  /** RegularExpression Id. */
  int TIPO_NUMERICO = 8;
  /** RegularExpression Id. */
  int TIPO_TEXTO = 9;
  /** RegularExpression Id. */
  int BREAK = 10;
  /** RegularExpression Id. */
  int WHILE = 11;
  /** RegularExpression Id. */
  int INICIO = 12;
  /** RegularExpression Id. */
  int FIM = 13;
  /** RegularExpression Id. */
  int VERDADEIRO = 14;
  /** RegularExpression Id. */
  int FALSO = 15;
  /** RegularExpression Id. */
  int IF = 16;
  /** RegularExpression Id. */
  int ELSE = 17;
  /** RegularExpression Id. */
  int ENTRADA = 18;
  /** RegularExpression Id. */
  int IMPRESSAO = 19;
  /** RegularExpression Id. */
  int TEXTO = 20;
  /** RegularExpression Id. */
  int LETRAS = 21;
  /** RegularExpression Id. */
  int NUMERO = 22;
  /** RegularExpression Id. */
  int DIGITO = 23;
  /** RegularExpression Id. */
  int VARIAVEL = 24;
  /** RegularExpression Id. */
  int ATRIBUICAO = 25;
  /** RegularExpression Id. */
  int CIFRAO = 26;
  /** RegularExpression Id. */
  int OP_LOGICO_E = 27;
  /** RegularExpression Id. */
  int OP_LOGICO_OU = 28;
  /** RegularExpression Id. */
  int OP_LOGICO_NEGACAO = 29;
  /** RegularExpression Id. */
  int OP_MAIOR_QUE = 30;
  /** RegularExpression Id. */
  int OP_MAIOR_OU_IGUAL = 31;
  /** RegularExpression Id. */
  int OP_MENOR_QUE = 32;
  /** RegularExpression Id. */
  int OP_MENOR_OU_IGUAL = 33;
  /** RegularExpression Id. */
  int OP_DIFERENTE = 34;
  /** RegularExpression Id. */
  int OP_IGUALDADE = 35;
  /** RegularExpression Id. */
  int ABRE_PARENTESES = 36;
  /** RegularExpression Id. */
  int FECHA_PARENTESES = 37;
  /** RegularExpression Id. */
  int ABRE_CHAVES = 38;
  /** RegularExpression Id. */
  int FECHA_CHAVES = 39;
  /** RegularExpression Id. */
  int ADICAO = 40;
  /** RegularExpression Id. */
  int SUBTRACAO = 41;
  /** RegularExpression Id. */
  int MULTIPLICACAO = 42;
  /** RegularExpression Id. */
  int DIVISAO = 43;
  /** RegularExpression Id. */
  int MODULO = 44;
  /** RegularExpression Id. */
  int FINAL_COMANDO = 45;
  /** RegularExpression Id. */
  int VIRGULA = 46;
  /** RegularExpression Id. */
  int ASPA = 47;
  /** RegularExpression Id. */
  int POTENCIA = 48;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\f\"",
    "<COMENTARIO_BLOC>",
    "<COMENTARIO_LIN>",
    "\"numerico\"",
    "\"texto\"",
    "\"break\"",
    "\"while\"",
    "\"inicio\"",
    "\"fim\"",
    "<VERDADEIRO>",
    "<FALSO>",
    "\"if\"",
    "\"else\"",
    "\"leia\"",
    "\"imprima\"",
    "<TEXTO>",
    "<LETRAS>",
    "<NUMERO>",
    "<DIGITO>",
    "<VARIAVEL>",
    "\"=\"",
    "\"$\"",
    "<OP_LOGICO_E>",
    "<OP_LOGICO_OU>",
    "<OP_LOGICO_NEGACAO>",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"!=\"",
    "\"==\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\";\"",
    "\",\"",
    "\"\\\"\"",
    "\"^\"",
  };

}
